project_id = "wijvuslujomodxsigyvv"

[functions.check-subscriptions]
verify_jwt = true

[functions.admin-create-tenant]
verify_jwt = true

[functions.admin-manage-tenant]
verify_jwt = true

[functions.admin-audit-logs]
verify_jwt = true

[functions.audit-log]
verify_jwt = true

[functions.sync_table_item]
verify_jwt = true

[functions.sync-table-item-hardened-2026]
verify_jwt = true

[functions.get-incremental-updates]
verify_jwt = true
