project_id = "wijvuslujomodxsigyvv"

[functions.check-subscriptions]
verify_jwt = true

[functions.admin-create-tenant]
verify_jwt = true

[functions.admin-manage-tenant]
verify_jwt = true

[functions.admin-audit-logs]
verify_jwt = true

[functions.audit-log]
verify_jwt = false
