export const PERMISSIONS = {
  SALES: {
    POS: "SALES:POS",
    VOID: "SALES:VOID",
    REFUND: "SALES:REFUND",
    DISCOUNT: "SALES:DISCOUNT",
  },
  INVENTORY: {
    VIEW: "INVENTORY:VIEW",
    ADJUST: "INVENTORY:ADJUST",
    COUNT: "INVENTORY:COUNT",
  },
  PURCHASES: {
    CREATE: "PURCHASES:CREATE",
    ORDER: "PURCHASES:ORDER",
    RECEIVE: "PURCHASES:RECEIVE",
    SUPPLIERS: "PURCHASES:SUPPLIERS",
  },
  CUSTOMERS: {
    VIEW: "CUSTOMERS:VIEW",
    CREATE: "CUSTOMERS:CREATE",
    EDIT: "CUSTOMERS:EDIT",
    DELETE: "CUSTOMERS:DELETE",
  },
  INVOICE: {
    ISSUE: "INVOICE:ISSUE",
    VOID: "INVOICE:VOID",
  },
  PRODUCTION: {
    ORDER: "PRODUCTION:ORDER",
    RECIPE: "PRODUCTION:RECIPE",
  },
  REPORTS: {
    VIEW: "REPORTS:VIEW",
    EXPORT: "REPORTS:EXPORT",
  },
  CONFIG: {
    TENANT: "CONFIG:TENANT",
    WAREHOUSE: "CONFIG:WAREHOUSE",
  },
  ADMIN: {
    USERS: "ADMIN:USERS",
    TENANT: "ADMIN:TENANT",
    SUBSCRIPTION: "ADMIN:SUBSCRIPTION",
  },
} as const;

export const DEFAULT_EMPLOYEE_PERMISSIONS = [
  PERMISSIONS.SALES.POS,
  PERMISSIONS.INVENTORY.VIEW,
  PERMISSIONS.CUSTOMERS.VIEW,
  PERMISSIONS.CUSTOMERS.CREATE,
] as const;

export const PERMISSION_MODULES = [
  "SALES",
  "INVENTORY",
  "PURCHASES",
  "CUSTOMERS",
  "INVOICE",
  "PRODUCTION",
  "REPORTS",
  "CONFIG",
  "ADMIN"
] as const;

export const EMPLOYEE_RESTRICTED_PERMISSIONS = [
  PERMISSIONS.REPORTS.VIEW,
  PERMISSIONS.REPORTS.EXPORT,
  PERMISSIONS.ADMIN.USERS,
  PERMISSIONS.ADMIN.TENANT,
  PERMISSIONS.ADMIN.SUBSCRIPTION,
  PERMISSIONS.CONFIG.TENANT,
  PERMISSIONS.CONFIG.WAREHOUSE,
  PERMISSIONS.SALES.VOID,
  PERMISSIONS.INVENTORY.ADJUST,
  PERMISSIONS.INVOICE.VOID,
  PERMISSIONS.CUSTOMERS.DELETE,
] as const;

export function getPermissionsByModule(module: keyof typeof PERMISSIONS): readonly string[] {
  return Object.values(PERMISSIONS[module]);
}

export function allPermissions(): string[] {
  return Object.values(PERMISSIONS).flatMap(m => Object.values(m));
}

export function isValidPermission(permission: string): boolean {
  return allPermissions().includes(permission);
}